// Generated by Wrangler on Sun Oct 13 2024 16:35:39 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
  ANTHROPIC_API_KEY: string;
  REMIX_PUBLIC_AUTH_URL: string;
  PROPELAUTH_API_KEY: string;
  PROPELAUTH_VERIFIER_KEY: string;
  PROPELAUTH_REDIRECT_URI: string;
  API_QUOTA: DurableObjectNamespace;
}
