// Generated by Wrangler by running `wrangler types`

interface Env {
	ANTHROPIC_API_KEY: string;
	REMIX_PUBLIC_AUTH_URL: string;
	PROPELAUTH_API_KEY: string;
	PROPELAUTH_VERIFIER_KEY: string;
	PROPELAUTH_REDIRECT_URI: string;
	SLACK_WEBHOOK_URL: string;
	API_QUOTA: DurableObjectNamespace /* APIQuota from api-quota */;
}
